# Generated by Django 4.2.5 on 2023-10-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
