# Generated by Django 4.2.5 on 2023-10-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Gold', 'Gold')], default='Free', max_length=30),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_cat', to='images.imagecategory'),
        ),
    ]
