# Generated by Django 4.2.5 on 2023-10-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_imagecategory_alter_membership_membership_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration_period',
            field=models.CharField(choices=[('Min', 'Min'), ('Days', 'Days'), ('Week', 'Week'), ('Months', 'Months')], default='Day', max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Gold', 'Gold'), ('Min', 'Min')], default='Free', max_length=30),
        ),
    ]
