# Generated by Django 4.2.5 on 2023-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_subscription_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Gold', 'Gold'), ('Min', 'Min')], default='Free', max_length=30)),
                ('dur', models.PositiveIntegerField(default=7)),
                ('period', models.CharField(choices=[('Days', 'Days'), ('Week', 'Week'), ('Months', 'Months')], default='Day', max_length=100)),
                ('pri', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
