# Generated by Django 4.2.5 on 2023-11-02 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0008_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.PositiveIntegerField(default=7, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration_period',
            field=models.CharField(choices=[('Min', 'Min'), ('Days', 'Days'), ('Week', 'Week'), ('Months', 'Months')], default='Day', max_length=100, verbose_name='Duration Unit'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Gold', 'Gold'), ('Min', 'Min')], default='Free', max_length=30, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='dur',
            field=models.PositiveIntegerField(default=7, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='test',
            name='period',
            field=models.CharField(choices=[('Days', 'Days'), ('Week', 'Week'), ('Months', 'Months')], default='Day', max_length=100, verbose_name='Duration Unit'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pri',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Min', 'Min')], default='Free', max_length=30, verbose_name='Membership Type'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to=settings.AUTH_USER_MODEL, verbose_name='username '),
        ),
    ]
