# Generated by Django 4.2.5 on 2023-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_alter_membership_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(max_length=255, verbose_name='Membership Type'),
        ),
    ]
