# Generated by Django 4.2.5 on 2023-11-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_membership_duration_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='pri',
        ),
    ]
