# Generated by Django 4.2.5 on 2023-11-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_remove_test_pri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
