# Generated by Django 4.2.5 on 2023-11-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('video_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videodata/')),
                ('description', models.TextField()),
                ('is_home_only', models.BooleanField(default=False)),
                ('video_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_cat', to='images.videocategory')),
            ],
        ),
    ]
