# Generated by Django 4.2.5 on 2023-11-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_videocategory_videomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='is_subscribers_only',
            new_name='is_home_only',
        ),
    ]
