# Generated by Django 4.2.5 on 2023-11-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_rename_is_subscribers_only_imagemodel_is_home_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='copy_img',
            field=models.ImageField(null=True, upload_to='copydata/'),
        ),
    ]
