# Generated by Django 4.2.5 on 2023-11-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_imagemodel_copy_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='copy_video',
            field=models.FileField(null=True, upload_to='copyvideodata/'),
        ),
    ]
