# Generated by Django 4.2.5 on 2023-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=200, verbose_name='Payment ID')),
                ('order_id', models.CharField(max_length=200, verbose_name='Order ID')),
                ('signature', models.CharField(blank=True, max_length=500, null=True, verbose_name='Signature')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('membership_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='username')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='username')),
                ('duration_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='username')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='username')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
            ],
        ),
    ]
