# Generated by Django 4.2.5 on 2023-10-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozarpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='duration_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='duration_period'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='membership_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='membership_type'),
        ),
    ]
